.TH "Artisan.Tools.AgError" 3 "Version 1.0" "AgTools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Artisan.Tools.AgError \- a framework for error codes mapping into string errors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBSUCCESS\fP = 0"
.br
.RI "Success\&. "
.ti -1c
.RI "static int \fBE_EXCEPTION\fP = 998"
.br
.RI "General exception error\&. "
.ti -1c
.RI "static int \fBE_OTHER\fP = 999"
.br
.RI "Other or unknown error\&. "
.in -1c
.SH "Detailed Description"
.PP 
a framework for error codes mapping into string errors\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AgTools from the source code\&.
