.TH "Artisan.Tools" 3 "Version 1.0" "AgTools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Artisan.Tools
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAgError\fP"
.br
.RI "a framework for error codes mapping into string errors\&. "
.ti -1c
.RI "class \fBAgErrorInfo\fP"
.br
.ti -1c
.RI "class \fBAgException\fP"
.br
.ti -1c
.RI "class \fBAgGlobals\fP"
.br
.RI "Global information\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AgTools from the source code\&.
