.TH "Artisan.Tools.Globalization" 3 "Version 1.0" "AgTools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Artisan.Tools.Globalization
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAgCountryCodes\fP"
.br
.RI "Static class which resolves country codes and country names\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AgTools from the source code\&.
