.TH "Artisan.Tools.Extensions" 3 "Version 1.0" "AgTools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Artisan.Tools.Extensions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDateTimeExtensions\fP"
.br
.RI "Here are some extensions for processing date-time objects\&. "
.ti -1c
.RI "class \fBIntExtensions\fP"
.br
.RI "General extensions for integers\&. "
.ti -1c
.RI "class \fBLongExtensions\fP"
.br
.RI "General extensions for long integers\&. "
.ti -1c
.RI "class \fBObjectExtensions\fP"
.br
.RI "Extensions for general objects and classes\&. These leverage reflection to help access props and other stuff\&. "
.ti -1c
.RI "class \fBStringExtensions\fP"
.br
.RI "Various string extensions\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AgTools from the source code\&.
