.TH "Artisan.Tools.AgGlobals" 3 "Version 1.0" "AgTools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Artisan.Tools.AgGlobals \- Global information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBHello\fP = 'Hello'"
.br
.RI "The hello string\&. "
.in -1c
.SH "Detailed Description"
.PP 
Global information\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AgTools from the source code\&.
