.TH "Artisan.Tools.Error_Handling" 3 "Version 1.0" "AgTools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Artisan.Tools.Error_Handling
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAgResult\fP"
.br
.RI "Allows us to return complex information from an API call\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AgTools from the source code\&.
